version: "3"

services:
  hackertools:
    container_name: hackertools
    ports:
      - "1337:1337"
    environment:
      PORT: 1337
      ENVIRONMENT: "development"
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["npm", "run", "dev"]
    volumes:
      - ./web/src:/app/src
      - ./web/views:/app/views
      - ./web/public:/app/public
      - ./web/parials:/app/parials
